Pathfinder_CharacterSheet_HostAddress = http://localhost:5020

### GET Todos List
GET {{Pathfinder_CharacterSheet_HostAddress}}/todos
Accept: application/json

### GET Todo by ID
GET {{Pathfinder_CharacterSheet_HostAddress}}/todos/1
Accept: application/json
